USERS TABLE:
CREATE TABLE USERS (
    USER_ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(150) NOT NULL UNIQUE,
    PHONE VARCHAR2(15) UNIQUE,
    ROLE VARCHAR2(20) NOT NULL
);
CUSTOMERS TABLE:
CREATE TABLE CUSTOMERS (
    CUSTOMER_ID NUMBER PRIMARY KEY,
    USER_ID NUMBER NOT NULL,
    CITY VARCHAR2(100),
    OCCUPATION VARCHAR2(100),

    CONSTRAINT FK_CUSTOMER_USER
        FOREIGN KEY (USER_ID)
        REFERENCES USERS(USER_ID)
);
OWNERS TABLE:
CREATE TABLE OWNERS (
    OWNER_ID NUMBER PRIMARY KEY,
    USER_ID NUMBER NOT NULL,
    CITY VARCHAR2(100),

    CONSTRAINT FK_OWNER_USER
        FOREIGN KEY (USER_ID)
        REFERENCES USERS(USER_ID)
);
PROPERTIES TABLE:
CREATE TABLE PROPERTIES (
    PROPERTY_ID NUMBER PRIMARY KEY,
    OWNER_ID NUMBER NOT NULL,
    TITLE VARCHAR2(200) NOT NULL,
    PROPERTY_TYPE VARCHAR2(50) NOT NULL,
    LOCATION VARCHAR2(150) NOT NULL,
    CITY VARCHAR2(100) NOT NULL,
    RENT NUMBER(10,2) NOT NULL,
    BEDROOMS NUMBER NOT NULL,
    AREA_SQFT NUMBER(10,2),
    FURNISHED_STATUS VARCHAR2(30),
    PARKING VARCHAR2(10),
    METRO_DISTANCE NUMBER(6,2),
    BUS_DISTANCE NUMBER(6,2),
    AVAILABLE_FROM DATE,
    DESCRIPTION VARCHAR2(1000),

    CONSTRAINT FK_PROPERTY_OWNER
        FOREIGN KEY (OWNER_ID)
        REFERENCES OWNERS(OWNER_ID)
);
USER PREFERENCES:
CREATE TABLE USER_PREFERENCES (
    PREFERENCE_ID NUMBER PRIMARY KEY,
    CUSTOMER_ID NUMBER NOT NULL,
    PREFERRED_LOCATION VARCHAR2(150),
    MIN_BUDGET NUMBER(10,2),
    MAX_BUDGET NUMBER(10,2),
    MIN_BEDROOMS NUMBER,
    PROPERTY_TYPE VARCHAR2(50),
    FURNISHED_STATUS VARCHAR2(30),
    PARKING_REQUIRED VARCHAR2(10),
    MAX_METRO_DISTANCE NUMBER(6,2),
    PREFERRED_AREA_SQFT NUMBER(10,2),

    CONSTRAINT FK_PREFERENCE_CUSTOMER
        FOREIGN KEY (CUSTOMER_ID)
        REFERENCES CUSTOMERS(CUSTOMER_ID)
);
SAVED PROPERTIES:
CREATE TABLE SAVED_PROPERTIES (
    SAVED_ID NUMBER PRIMARY KEY,
    CUSTOMER_ID NUMBER NOT NULL,
    PROPERTY_ID NUMBER NOT NULL,

    CONSTRAINT FK_SAVED_CUSTOMER
        FOREIGN KEY (CUSTOMER_ID)
        REFERENCES CUSTOMERS(CUSTOMER_ID),

    CONSTRAINT FK_SAVED_PROPERTY
        FOREIGN KEY (PROPERTY_ID)
        REFERENCES PROPERTIES(PROPERTY_ID)
);
RENTAL REQUESTS:
CREATE TABLE RENTAL_REQUESTS (
    REQUEST_ID NUMBER PRIMARY KEY,
    CUSTOMER_ID NUMBER NOT NULL,
    PROPERTY_ID NUMBER NOT NULL,
    REQUEST_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    STATUS VARCHAR2(20) NOT NULL,
    MESSAGE VARCHAR2(500),

    CONSTRAINT FK_REQUEST_CUSTOMER
        FOREIGN KEY (CUSTOMER_ID)
        REFERENCES CUSTOMERS(CUSTOMER_ID),

    CONSTRAINT FK_REQUEST_PROPERTY
        FOREIGN KEY (PROPERTY_ID)
        REFERENCES PROPERTIES(PROPERTY_ID)
);
RECOMMENDATIONS:
CREATE TABLE RECOMMENDATIONS (
    RECOMMENDATION_ID NUMBER PRIMARY KEY,
    CUSTOMER_ID NUMBER NOT NULL,
    PROPERTY_ID NUMBER NOT NULL,
    MATCH_SCORE NUMBER(5,2),
    PREDICTED_RENT NUMBER(10,2),
    RECOMMENDATION_REASON VARCHAR2(500),

    CONSTRAINT FK_RECOMMENDATION_CUSTOMER
        FOREIGN KEY (CUSTOMER_ID)
        REFERENCES CUSTOMERS(CUSTOMER_ID),

    CONSTRAINT FK_RECOMMENDATION_PROPERTY
        FOREIGN KEY (PROPERTY_ID)
        REFERENCES PROPERTIES(PROPERTY_ID)
);
NOW TO CHECK WHEATHER ALL THE TABLES HAVE BEEN CREATED:
SELECT TABLE_NAME
FROM USER_TABLES
WHERE TABLE_NAME IN (
    'USERS',
    'CUSTOMERS',
    'OWNERS',
    'PROPERTIES',
    'USER_PREFERENCES',
    'SAVED_PROPERTIES',
    'RENTAL_REQUESTS',
    'RECOMMENDATIONS'
)
ORDER BY TABLE_NAME;
