                      USERS INSERTION:
INSERT INTO USERS (USER_ID, NAME, EMAIL, PHONE, ROLE)
VALUES (1, 'Vamshika', 'vamshika@gmail.com', '9876543210', 'CUSTOMER');

INSERT INTO USERS (USER_ID, NAME, EMAIL, PHONE, ROLE)
VALUES (2, 'Ravi Kumar', 'ravi@gmail.com', '9876543211', 'OWNER');

INSERT INTO USERS (USER_ID, NAME, EMAIL, PHONE, ROLE)
VALUES (3, 'Priya Sharma', 'priya@gmail.com', '9876543212', 'CUSTOMER');

INSERT INTO USERS (USER_ID, NAME, EMAIL, PHONE, ROLE)
VALUES (4, 'Suresh Reddy', 'suresh@gmail.com', '9876543213', 'OWNER');

INSERT INTO USERS (USER_ID, NAME, EMAIL, PHONE, ROLE)
VALUES (5, 'Admin', 'admin@rental.com', '9876543214', 'ADMIN');
COMMIT;
SELECT * FROM USERS;
                  INSERT CUSTOMERS:
INSERT INTO CUSTOMERS (CUSTOMER_ID, USER_ID, CITY, OCCUPATION)
VALUES (101, 1, 'Hyderabad', 'Student');

INSERT INTO CUSTOMERS (CUSTOMER_ID, USER_ID, CITY, OCCUPATION)
VALUES (102, 3, 'Hyderabad', 'Software Engineer');

COMMIT;
SELECT * FROM CUSTOMERS;
                INSERT OWNERS:
                INSERT INTO OWNERS (OWNER_ID, USER_ID, CITY)
VALUES (201, 2, 'Hyderabad');

INSERT INTO OWNERS (OWNER_ID, USER_ID, CITY)
VALUES (202, 4, 'Hyderabad');

COMMIT;
    SELECT * FROM OWNERS;
    INSERT PROPERTIES:   
    INSERT INTO PROPERTIES
(PROPERTY_ID, OWNER_ID, TITLE, PROPERTY_TYPE, LOCATION, CITY, RENT,
 BEDROOMS, AREA_SQFT, FURNISHED_STATUS, PARKING, METRO_DISTANCE,
 BUS_DISTANCE, AVAILABLE_FROM, DESCRIPTION)
VALUES
(301, 201, '2BHK Flat in Kondapur', 'Apartment',
 'Kondapur', 'Hyderabad', 20000,
 2, 1200, 'Semi-Furnished', 'Yes', 2.5,
 0.5, DATE '2026-10-01',
 'Spacious 2BHK apartment near IT offices.');

INSERT INTO PROPERTIES
(PROPERTY_ID, OWNER_ID, TITLE, PROPERTY_TYPE, LOCATION, CITY, RENT,
 BEDROOMS, AREA_SQFT, FURNISHED_STATUS, PARKING, METRO_DISTANCE,
 BUS_DISTANCE, AVAILABLE_FROM, DESCRIPTION)
VALUES
(302, 201, '1BHK Apartment in Madhapur', 'Apartment',
 'Madhapur', 'Hyderabad', 16000,
 1, 850, 'Furnished', 'Yes', 1.8,
 0.3, DATE '2026-10-05',
 'Fully furnished 1BHK near Madhapur IT corridor.');

INSERT INTO PROPERTIES
(PROPERTY_ID, OWNER_ID, TITLE, PROPERTY_TYPE, LOCATION, CITY, RENT,
 BEDROOMS, AREA_SQFT, FURNISHED_STATUS, PARKING, METRO_DISTANCE,
 BUS_DISTANCE, AVAILABLE_FROM, DESCRIPTION)
VALUES
(303, 202, '2BHK Flat in Gachibowli', 'Apartment',
 'Gachibowli', 'Hyderabad', 23000,
 2, 1300, 'Semi-Furnished', 'Yes', 3.0,
 0.7, DATE '2026-10-10',
 'Modern 2BHK apartment close to offices and restaurants.');

INSERT INTO PROPERTIES
(PROPERTY_ID, OWNER_ID, TITLE, PROPERTY_TYPE, LOCATION, CITY, RENT,
 BEDROOMS, AREA_SQFT, FURNISHED_STATUS, PARKING, METRO_DISTANCE,
 BUS_DISTANCE, AVAILABLE_FROM, DESCRIPTION)
VALUES
(304, 202, '3BHK House in Kukatpally', 'Independent House',
 'Kukatpally', 'Hyderabad', 28000,
 3, 1700, 'Unfurnished', 'Yes', 2.2,
 0.4, DATE '2026-10-15',
 'Large independent house suitable for a family.');

INSERT INTO PROPERTIES
(PROPERTY_ID, OWNER_ID, TITLE, PROPERTY_TYPE, LOCATION, CITY, RENT,
 BEDROOMS, AREA_SQFT, FURNISHED_STATUS, PARKING, METRO_DISTANCE,
 BUS_DISTANCE, AVAILABLE_FROM, DESCRIPTION)
VALUES
(305, 201, '2BHK Flat in Miyapur', 'Apartment',
 'Miyapur', 'Hyderabad', 18000,
 2, 1150, 'Furnished', 'Yes', 1.2,
 0.6, DATE '2026-10-03',
 'Furnished 2BHK apartment close to metro station.');

INSERT INTO PROPERTIES
(PROPERTY_ID, OWNER_ID, TITLE, PROPERTY_TYPE, LOCATION, CITY, RENT,
 BEDROOMS, AREA_SQFT, FURNISHED_STATUS, PARKING, METRO_DISTANCE,
 BUS_DISTANCE, AVAILABLE_FROM, DESCRIPTION)
VALUES
(306, 202, '2BHK Apartment in Manikonda', 'Apartment',
 'Manikonda', 'Hyderabad', 19000,
 2, 1250, 'Semi-Furnished', 'No', 4.0,
 0.8, DATE '2026-10-12',
 'Comfortable 2BHK apartment in a residential area.');

COMMIT;
SELECT * FROM PROPERTIES;
                      USER PREFERENCES
 INSERT INTO USER_PREFERENCES
(PREFERENCE_ID, CUSTOMER_ID, PREFERRED_LOCATION, MIN_BUDGET,
 MAX_BUDGET, MIN_BEDROOMS, PROPERTY_TYPE, FURNISHED_STATUS,
 PARKING_REQUIRED, MAX_METRO_DISTANCE, PREFERRED_AREA_SQFT)
VALUES
(401, 101, 'Kondapur', 15000, 25000, 2, 'Apartment',
 'Semi-Furnished', 'Yes', 3.0, 1100);

INSERT INTO USER_PREFERENCES
(PREFERENCE_ID, CUSTOMER_ID, PREFERRED_LOCATION, MIN_BUDGET,
 MAX_BUDGET, MIN_BEDROOMS, PROPERTY_TYPE, FURNISHED_STATUS,
 PARKING_REQUIRED, MAX_METRO_DISTANCE, PREFERRED_AREA_SQFT)
VALUES
(402, 102, 'Gachibowli', 18000, 30000, 2, 'Apartment',
 'Furnished', 'Yes', 4.0, 1200);

COMMIT;
SELECT * FROM USER_PREFERENCES;
                    SAVED PROPERTIES:
 INSERT INTO SAVED_PROPERTIES
(SAVED_ID, CUSTOMER_ID, PROPERTY_ID)
VALUES (501, 101, 301);

INSERT INTO SAVED_PROPERTIES
(SAVED_ID, CUSTOMER_ID, PROPERTY_ID)
VALUES (502, 101, 305);

INSERT INTO SAVED_PROPERTIES
(SAVED_ID, CUSTOMER_ID, PROPERTY_ID)
VALUES (503, 102, 303);

INSERT INTO SAVED_PROPERTIES
(SAVED_ID, CUSTOMER_ID, PROPERTY_ID)
VALUES (504, 102, 306);

COMMIT;
SELECT * FROM SAVED_PROPERTIES;
                   RENTAL REQUESTS
 INSERT INTO RENTAL_REQUESTS
(REQUEST_ID, CUSTOMER_ID, PROPERTY_ID, STATUS, MESSAGE)
VALUES
(601, 101, 301, 'PENDING',
 'I am interested in this property and would like to know more details.');

INSERT INTO RENTAL_REQUESTS
(REQUEST_ID, CUSTOMER_ID, PROPERTY_ID, STATUS, MESSAGE)
VALUES
(602, 102, 303, 'ACCEPTED',
 'I would like to schedule a visit to this property.');

INSERT INTO RENTAL_REQUESTS
(REQUEST_ID, CUSTOMER_ID, PROPERTY_ID, STATUS, MESSAGE)
VALUES
(603, 101, 305, 'REJECTED',
 'Please let me know if the property is still available.');

COMMIT;
SELECT * FROM RENTAL_REQUESTS;
                     RECOMMENDATION
 INSERT INTO RECOMMENDATIONS
(RECOMMENDATION_ID, CUSTOMER_ID, PROPERTY_ID, MATCH_SCORE, PREDICTED_RENT, RECOMMENDATION_REASON)
VALUES
(701, 101, 301, 92.50, 19800,
 'Excellent match for preferred location, budget, bedrooms and parking.');

INSERT INTO RECOMMENDATIONS
(RECOMMENDATION_ID, CUSTOMER_ID, PROPERTY_ID, MATCH_SCORE, PREDICTED_RENT, RECOMMENDATION_REASON)
VALUES
(702, 101, 305, 88.00, 18500,
 'Good match for budget, bedrooms, furnished status and metro distance.');

INSERT INTO RECOMMENDATIONS
(RECOMMENDATION_ID, CUSTOMER_ID, PROPERTY_ID, MATCH_SCORE, PREDICTED_RENT, RECOMMENDATION_REASON)
VALUES
(703, 101, 306, 76.50, 19500,
 'Matches budget and bedroom preference with suitable area.');

INSERT INTO RECOMMENDATIONS
(RECOMMENDATION_ID, CUSTOMER_ID, PROPERTY_ID, MATCH_SCORE, PREDICTED_RENT, RECOMMENDATION_REASON)
VALUES
(704, 102, 303, 94.00, 22500,
 'Excellent match for preferred location, budget, bedrooms and parking.');

INSERT INTO RECOMMENDATIONS
(RECOMMENDATION_ID, CUSTOMER_ID, PROPERTY_ID, MATCH_SCORE, PREDICTED_RENT, RECOMMENDATION_REASON)
VALUES
(705, 102, 301, 82.50, 20000,
 'Good match for budget, bedrooms and preferred apartment type.');

INSERT INTO RECOMMENDATIONS
(RECOMMENDATION_ID, CUSTOMER_ID, PROPERTY_ID, MATCH_SCORE, PREDICTED_RENT, RECOMMENDATION_REASON)
VALUES
(706, 102, 306, 79.00, 19000,
 'Matches budget, bedrooms and metro-distance requirement.');

COMMIT;
SELECT *
FROM RECOMMENDATIONS
ORDER BY RECOMMENDATION_ID;
verify customers+preferences
SELECT
    c.CUSTOMER_ID,
    u.NAME,
    c.CITY,
    c.OCCUPATION,
    p.PREFERRED_LOCATION,
    p.MIN_BUDGET,
    p.MAX_BUDGET,
    p.MIN_BEDROOMS
FROM CUSTOMERS c
JOIN USERS u
    ON c.USER_ID = u.USER_ID
JOIN USER_PREFERENCES p
    ON c.CUSTOMER_ID = p.CUSTOMER_ID;
VERIFY OWNERS+PROPERTIES:
SELECT
    o.OWNER_ID,
    u.NAME AS OWNER_NAME,
    o.CITY,
    p.PROPERTY_ID,
    p.TITLE,
    p.LOCATION,
    p.RENT,
    p.BEDROOMS
FROM OWNERS o
JOIN USERS u
    ON o.USER_ID = u.USER_ID
JOIN PROPERTIES p
    ON o.OWNER_ID = p.OWNER_ID
ORDER BY o.OWNER_ID, p.PROPERTY_ID;
VERIFY SAVED PROPERTIES:
SELECT
    s.SAVED_ID,
    u.NAME AS CUSTOMER_NAME,
    p.PROPERTY_ID,
    p.TITLE,
    p.LOCATION,
    p.RENT
FROM SAVED_PROPERTIES s
JOIN CUSTOMERS c
    ON s.CUSTOMER_ID = c.CUSTOMER_ID
JOIN USERS u
    ON c.USER_ID = u.USER_ID
JOIN PROPERTIES p
    ON s.PROPERTY_ID = p.PROPERTY_ID
ORDER BY s.SAVED_ID;
       VERIFY RENTAL REQUESTS:
       SELECT
    r.REQUEST_ID,
    cu.NAME AS CUSTOMER_NAME,
    p.TITLE AS PROPERTY_TITLE,
    ou.NAME AS OWNER_NAME,
    r.STATUS,
    r.REQUEST_DATE,
    r.MESSAGE
FROM RENTAL_REQUESTS r
JOIN CUSTOMERS c
    ON r.CUSTOMER_ID = c.CUSTOMER_ID
JOIN USERS cu
    ON c.USER_ID = cu.USER_ID
JOIN PROPERTIES p
    ON r.PROPERTY_ID = p.PROPERTY_ID
JOIN OWNERS o
    ON p.OWNER_ID = o.OWNER_ID
JOIN USERS ou
    ON o.USER_ID = ou.USER_ID
ORDER BY r.REQUEST_ID;
VERIFY AI RECOMMENDATIONS
SELECT
    r.RECOMMENDATION_ID,
    u.NAME AS CUSTOMER_NAME,
    p.TITLE AS PROPERTY_TITLE,
    p.LOCATION,
    p.RENT AS ACTUAL_RENT,
    r.PREDICTED_RENT,
    r.MATCH_SCORE,
    r.RECOMMENDATION_REASON
FROM RECOMMENDATIONS r
JOIN CUSTOMERS c
    ON r.CUSTOMER_ID = c.CUSTOMER_ID
JOIN USERS u
    ON c.USER_ID = u.USER_ID
JOIN PROPERTIES p
    ON r.PROPERTY_ID = p.PROPERTY_ID
ORDER BY r.CUSTOMER_ID, r.MATCH_SCORE DESC;
